name: Rodar Bot do Telegram

on:
  workflow_dispatch:  # Permite iniciar manualmente
  push:               # Inicia quando você atualiza o código
    branches: [ main ]

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar o código
        uses: actions/checkout@v4

      - name: Instalar o Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar bibliotecas
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Rodar o bot
        env:
          # Passa o segredo para o código como variável de ambiente
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        run: python main.py
        
